### ISSUE TITLE
Add default settings for wifi to improve the performance

### ISSUE THREAD

**Issue by abhijit-mahajani-imgtec** [CreatorDev/Ci40-platform-feed#120]
Ensigma has advised some settings to be added as the default settings for improving the wifi performance

sysctl -w net.core.rmem_default=10485760
sysctl -w net.core.rmem_max=10485760
echo e > /sys/class/net/wlan0/queues/rx-0/rps_cpus  (setting rps_cpus to ‘c’ gave identical results)
sysctl -w net.core.wmem_default=10485760
sysctl -w net.core.wmem_max=10485760
sysctl -w net.ipv4.tcp_wmem=10485760

These can be added in the init script kept in uccp420wlan feed.

**Comment by francois-berder-imgtec** [comment]
This line cannot be added to the init script as the wlan0 interface does not exist. 

```echo e > /sys/class/net/wlan0/queues/rx-0/rps_cpus (setting rps_cpus to ‘c’ gave identical results)```

**Comment by Avinash95** [comment]
https://wiki.openwrt.org/doc/techref/hotplug this might be useful to execute echo e command once  wlan interface comes up

**Comment by Avinash95** [comment]
Can we put this scripts in /etc/uci-defaults as we want this to be done once and not every time device boots?

**Comment by francois-berder-imgtec** [comment]
@Avinash95 Indeed it worked !
